// lib/core/isar/schemas/transaction.dart
//
// PaisaPlus – Transaction Isar Schema
// ------------------------------------
// This is the core financial record. Every expense, income, and transfer the
// user enters lives here — exclusively on-device in the encrypted Isar DB.
//
// Design decisions:
//  • amountInPaise (int) — store money as integer paise (1 INR = 100 paise) to
//    avoid floating-point rounding errors entirely. Display layer divides by 100.
//  • TransactionType enum — expense | income | transfer. Transfer creates TWO
//    linked Transaction records (debit from source, credit to destination) tied
//    by transferPairId so they can be found and deleted together.
//  • categoryId / accountId / toAccountId — Isar integer foreign keys (manual
//    links; we don't use Isar Links to keep queries simple and predictable).
//  • tags — stored as a List<String> embedded directly; avoids a join table for
//    a feature that is essentially read-only after creation.
//  • recurringRuleId — nullable; set when this transaction was auto-generated
//    from a RecurringRule. Lets us find and delete all instances of a rule.
//  • note / attachmentPath — attachmentPath stores the LOCAL file path to a
//    photo the user captured. Never uploaded anywhere.
//  • isDeleted (soft delete) — safer than hard delete; lets the UI animate
//    removal and provides a 30-day recycle bin in Phase 3 polish.
//  • All date/time fields stored as DateTime (Isar stores as UTC int internally).

import 'package:isar/isar.dart';

part 'transaction.g.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────────

/// The three fundamental types of financial movements in PaisaPlus.
enum TransactionType {
  expense,
  income,
  transfer,
}

/// How a transaction was created — used for filtering and audit in the UI.
enum TransactionEntryMode {
  manual,      // User typed it in
  recurring,   // Auto-generated from a RecurringRule
  imported,    // Future: CSV import (Phase 3)
}

// ─────────────────────────────────────────────────────────────────────────────
// Schema
// ─────────────────────────────────────────────────────────────────────────────

@Collection()
class Transaction {
  // ── Identity ───────────────────────────────────────────────────────────────
  Id id = Isar.autoIncrement;

  /// Stable UUID string — used externally (export, backup matching).
  /// Generated via uuid package on creation. Never changes after creation.
  @Index(unique: true)
  late String uuid;

  // ── Core Financial Data ────────────────────────────────────────────────────

  /// Amount stored in paise (smallest INR unit). 1 INR = 100 paise.
  /// Always positive. TransactionType determines the sign for accounting.
  /// Example: ₹1,234.50 → amountInPaise = 123450
  late int amountInPaise;

  @enumerated
  late TransactionType type;

  // ── Relationships (manual int FK — no Isar Links) ─────────────────────────

  /// ID of the Category this transaction belongs to.
  /// Required for expense and income; for transfers, use the "Transfer" system category.
  late int categoryId;

  /// ID of the Account money is taken FROM (expense) or added TO (income).
  /// For transfers: this is the SOURCE account.
  late int accountId;

  /// Only set for TransactionType.transfer — the DESTINATION account ID.
  @Index()
  int? toAccountId;

  /// For transfers: both the debit and credit Transaction share this UUID.
  /// Allows fetching the pair for display ("Transfer to HDFC") and atomic delete.
  @Index()
  String? transferPairId;

  // ── Date & Time ────────────────────────────────────────────────────────────

  /// The date the transaction actually occurred (user-entered, may differ from createdAt).
  @Index()
  late DateTime transactionDate;

  /// When this record was inserted into Isar.
  late DateTime createdAt;

  /// When this record was last modified.
  late DateTime updatedAt;

  // ── Optional Metadata ──────────────────────────────────────────────────────

  /// User-written description. Shown on list cards and detail screen.
  String? note;

  /// Local absolute file path to an attached photo (from camera or gallery).
  /// The file lives in app's private directory — never uploaded anywhere.
  String? attachmentPath;

  /// Free-form tags typed by user. Stored inline as strings.
  /// Examples: ["work", "reimbursable", "tax-deductible"]
  List<String> tags = [];

  /// Payee / merchant name. India-first: UPI VPA or merchant name from user.
  String? payee;

  // ── Recurring ──────────────────────────────────────────────────────────────

  /// If this transaction was generated by a RecurringRule, its ID goes here.
  /// Null for manually-entered transactions.
  @Index()
  int? recurringRuleId;

  /// If this transaction is a payment for a loan/debt, its ID goes here.
  @Index()
  int? loanId;

  @enumerated
  TransactionEntryMode entryMode = TransactionEntryMode.manual;

  // ── Geolocation (optional, Phase 3) ───────────────────────────────────────

  /// Latitude stored as microdegrees (int) to avoid float. 0 means not set.
  /// Example: 19.0760° N → 19076000
  int? locationLatMicro;

  /// Longitude stored as microdegrees (int). 0 means not set.
  int? locationLngMicro;

  /// Human-readable location name (e.g. "Bandra, Mumbai"). User-filled or
  /// reverse-geocoded locally.
  String? locationName;

  // ── Soft Delete ────────────────────────────────────────────────────────────

  /// Soft-delete flag. Deleted transactions are hidden from UI but retained
  /// for 30 days before permanent purge (Phase 5 polish).
  @Index()
  bool isDeleted = false;

  /// When the soft-delete happened (for 30-day purge timer).
  DateTime? deletedAt;

  // ── Helpers ────────────────────────────────────────────────────────────────

  /// Convenience: amount as double INR for display.
  /// Always use amountInPaise for storage and arithmetic.
  double get amountInRupees => amountInPaise / 100.0;

  /// True when this transaction is the DEBIT leg of a transfer pair.
  bool get isTransferDebit =>
      type == TransactionType.transfer && toAccountId != null;

  /// True when this transaction is the CREDIT leg of a transfer pair.
  bool get isTransferCredit =>
      type == TransactionType.transfer && toAccountId == null;
}